export const tableMockData = [
  {
    id: 1,
    first_name: 'Waylin',
    last_name: 'Roussel',
    email: 'wroussel0@issuu.com',
    gender: 'Polygender',
    ip_address: '201.82.12.178',
  },
  {
    id: 2,
    first_name: 'Dallis',
    last_name: 'Jansens',
    email: 'djansens1@fema.gov',
    gender: 'Agender',
    ip_address: '177.186.90.75',
  },
  {
    id: 3,
    first_name: 'Valera',
    last_name: 'Kitto',
    email: 'vkitto2@github.com',
    gender: 'Polygender',
    ip_address: '200.222.127.150',
  },
  {
    id: 4,
    first_name: 'Frayda',
    last_name: 'Townley',
    email: 'ftownley3@biblegateway.com',
    gender: 'Bigender',
    ip_address: '173.119.52.208',
  },
  {
    id: 5,
    first_name: 'Andras',
    last_name: 'Hardaway',
    email: 'ahardaway4@nymag.com',
    gender: 'Genderqueer',
    ip_address: '197.212.88.136',
  },
];
